name: Auto Deploy Golang
   on:
     push:
       branches: [ main ]

   jobs:
     deploy:
       runs-on: ubuntu-latest
       steps:
         - name: SSH & Deploy
           uses: appleboy/ssh-action@v1.3.0
           with:
             host: ${{ secrets.SERVER_IP }}
             username: ${{ secrets.SSH_USERNAME }}
             key: ${{ secrets.SSH_KEY }}
             script: |
               cd /home/forall/gin-server
               git pull origin main
               go build -o gin-server
               sudo systemctl restart myapp.service
